import { StyleSheet } from "react-native";
import { COLORS } from "./theme";

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  safeArea: { flex: 1, backgroundColor: COLORS.background },
  pageContent: { paddingHorizontal: 22, paddingBottom: 28 },
  pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] },
  header: {
    minHeight: 78,
    paddingTop: 12,
    paddingBottom: 13,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  eyebrow: {
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.3,
  },
  greeting: { color: COLORS.ink, fontSize: 28, lineHeight: 34, fontWeight: "700", marginTop: 3 },
  wave: { color: COLORS.orange, fontSize: 23 },
  pageTitle: { color: COLORS.ink, fontSize: 28, lineHeight: 34, fontWeight: "700", marginTop: 3 },
  headerMark: {
    width: 43,
    height: 43,
    borderRadius: 15,
    backgroundColor: COLORS.green,
    alignItems: "center",
    justifyContent: "center",
  },
  summaryCard: {
    marginTop: 10,
    backgroundColor: COLORS.greenDark,
    borderRadius: 24,
    paddingHorizontal: 21,
    paddingTop: 22,
    paddingBottom: 17,
    overflow: "hidden",
  },
  summaryText: { zIndex: 1 },
  summaryEyebrow: { color: "#B8CBB9", fontSize: 15, fontWeight: "700", letterSpacing: 1.4 },
  summaryTitle: { color: COLORS.white, fontSize: 27, fontWeight: "700", lineHeight: 31, marginTop: 7 },
  summaryCaption: { color: "#CDDBCE", fontSize: 12, marginTop: 6 },
  summaryIllustration: { position: "absolute", right: 15, top: 34, opacity: 0.9 },
  trackLine: { backgroundColor: "#78927C", height: 2, width: 76, marginTop: 5 },
  trackLineShort: { backgroundColor: "#78927C", height: 2, width: 76, marginTop: 4 },
  summaryStats: {
    flexDirection: "row",
    alignItems: "center",
    borderTopColor: "rgba(255,255,255,0.17)",
    borderTopWidth: 1,
    marginTop: 20,
    paddingTop: 13,
  },
  summaryNumber: { color: COLORS.white, fontSize: 20, fontWeight: "700" },
  summaryLabel: { color: "#B8CBB9", fontSize: 8, fontWeight: "700", letterSpacing: 1, marginTop: 1 },
  summaryDivider: { height: 29, width: 1, backgroundColor: "rgba(255,255,255,0.2)", marginHorizontal: 22 },
  summaryAdd: {
    width: 37,
    height: 37,
    borderRadius: 14,
    backgroundColor: "#D7E4D7",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: "auto",
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 27,
    marginBottom: 13,
  },
  sectionTitle: { color: COLORS.ink, fontSize: 18, fontWeight: "700" },
  sectionSubtitle: { color: COLORS.muted, fontSize: 11, marginTop: 4 },
  livePill: {
    height: 26,
    borderRadius: 13,
    paddingHorizontal: 9,
    backgroundColor: COLORS.paleGreen,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  liveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: COLORS.green },
  liveText: { color: COLORS.green, fontSize: 8, fontWeight: "700", letterSpacing: 0.6 },
  sightingList: { gap: 10 },
  sightingCard: {
    minHeight: 89,
    backgroundColor: COLORS.white,
    borderRadius: 18,
    padding: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderWidth: 1,
    borderColor: "#EEEFE9",
  },
  sightingPhoto: { width: 62, height: 66, borderRadius: 12, backgroundColor: COLORS.pale },
  trainBadge: {
    width: 62,
    height: 66,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.paleGreen,
  },
  sightingDetails: { flex: 1, minWidth: 0 },
  sightingTopline: { flexDirection: "row", alignItems: "center", gap: 7 },
  topsNumber: { color: COLORS.ink, fontSize: 19, fontWeight: "700", letterSpacing: 0.3 },
  classTag: { backgroundColor: COLORS.pale, borderRadius: 5, paddingHorizontal: 5, paddingVertical: 3 },
  classTagText: { color: COLORS.muted, fontSize: 7, fontWeight: "700", letterSpacing: 0.4 },
  sightingLocation: { color: "#49584E", fontSize: 11, fontWeight: "600", marginTop: 5 },
  destinationRow: { flexDirection: "row", alignItems: "center", gap: 3, marginTop: 3 },
  destinationText: { color: COLORS.muted, fontSize: 10, flexShrink: 1 },
  sightingDate: { color: "#939B94", fontSize: 9, marginTop: 4 },
  iconButton: { width: 29, height: 34, alignItems: "center", justifyContent: "center" },
  listLimitNote: { color: COLORS.muted, fontSize: 11, textAlign: "center", marginTop: 4 },
  emptyCard: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 21,
    paddingHorizontal: 22,
    paddingVertical: 25,
    alignItems: "center",
  },
  emptyIcon: {
    width: 58,
    height: 58,
    borderRadius: 20,
    backgroundColor: COLORS.paleGreen,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTitle: { color: COLORS.ink, fontSize: 17, fontWeight: "700", marginTop: 14 },
  emptyCopy: { color: COLORS.muted, fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 7 },
  primaryButton: {
    minHeight: 48,
    paddingHorizontal: 17,
    backgroundColor: COLORS.green,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 17,
  },
  primaryButtonText: { color: COLORS.white, fontSize: 13, fontWeight: "700" },
  privacyNote: { color: COLORS.muted, fontSize: 10, textAlign: "center", marginTop: 16 },
  formIntro: { color: COLORS.muted, fontSize: 13, lineHeight: 19, marginTop: 1, marginBottom: 17 },
  formCard: {
    backgroundColor: COLORS.white,
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderWidth: 1,
    borderColor: "#EEEFE9",
  },
  formStep: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 16 },
  stepNumber: {
    width: 31,
    height: 31,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.paleGreen,
  },
  stepNumberText: { color: COLORS.green, fontSize: 10, fontWeight: "700" },
  formSectionTitle: { color: COLORS.ink, fontSize: 14, fontWeight: "700" },
  formSectionCopy: { color: COLORS.muted, fontSize: 10, marginTop: 2 },
  field: { marginBottom: 13 },
  fieldLabelRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 7 },
  fieldLabel: { color: "#445249", fontSize: 11, fontWeight: "700" },
  fieldHint: { color: "#9BA29C", fontSize: 8, fontWeight: "700", letterSpacing: 0.6 },
  input: {
    height: 47,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.line,
    backgroundColor: "#FCFCFA",
    color: COLORS.ink,
    paddingHorizontal: 13,
    fontSize: 13,
  },
  classPreview: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: -4, marginBottom: 2 },
  classPreviewText: { color: COLORS.muted, fontSize: 10 },
  classPreviewStrong: { color: COLORS.green, fontWeight: "700" },
  formSeparator: { height: 1, backgroundColor: COLORS.line, marginVertical: 17 },
  dateNote: {
    minHeight: 37,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderRadius: 10,
    backgroundColor: "#F2F6F1",
    paddingHorizontal: 10,
    marginTop: 1,
  },
  dateNoteText: { color: "#58705F", fontSize: 10, flex: 1 },
  photoButton: {
    minHeight: 65,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderStyle: "dashed",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    gap: 10,
  },
  photoButtonIcon: { width: 39, height: 39, borderRadius: 12, backgroundColor: COLORS.paleGreen, alignItems: "center", justifyContent: "center" },
  photoButtonTextWrap: { flex: 1 },
  photoButtonTitle: { color: COLORS.ink, fontSize: 11, fontWeight: "700" },
  photoButtonHint: { color: COLORS.muted, fontSize: 9, marginTop: 3 },
  photoPreviewWrap: { position: "relative", marginBottom: 1 },
  photoPreview: { width: "100%", height: 180, borderRadius: 14, backgroundColor: COLORS.pale },
  removePhoto: {
    position: "absolute",
    top: 9,
    right: 9,
    width: 31,
    height: 31,
    borderRadius: 11,
    backgroundColor: "rgba(24,40,32,0.75)",
    alignItems: "center",
    justifyContent: "center",
  },
  saveButton: { marginTop: 18, minHeight: 50 },
  disabledButton: { opacity: 0.7 },
  formPrivacy: { color: COLORS.muted, fontSize: 10, textAlign: "center", marginTop: 15 },
  profileCard: {
    marginTop: 11,
    backgroundColor: COLORS.white,
    borderRadius: 22,
    alignItems: "center",
    paddingTop: 22,
    paddingHorizontal: 18,
    paddingBottom: 17,
    borderWidth: 1,
    borderColor: "#EEEFE9",
  },
  profileAvatar: {
    width: 66,
    height: 66,
    borderRadius: 23,
    backgroundColor: COLORS.paleGreen,
    alignItems: "center",
    justifyContent: "center",
  },
  profileName: { color: COLORS.ink, fontSize: 18, fontWeight: "700", marginTop: 10 },
  profileBio: { color: COLORS.muted, fontSize: 11, marginTop: 4 },
  localBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: COLORS.paleGreen,
    borderRadius: 10,
    paddingHorizontal: 9,
    paddingVertical: 5,
    marginTop: 10,
  },
  localBadgeText: { color: COLORS.green, fontSize: 8, fontWeight: "700", letterSpacing: 0.5 },
  profileRule: { alignSelf: "stretch", height: 1, backgroundColor: COLORS.line, marginTop: 19 },
  profileStats: { flexDirection: "row", alignItems: "center", justifyContent: "space-around", alignSelf: "stretch", paddingTop: 15 },
  profileStat: { flex: 1, alignItems: "center" },
  profileStatNumber: { color: COLORS.ink, fontSize: 19, fontWeight: "700" },
  profileStatLabel: { color: COLORS.muted, fontSize: 8, fontWeight: "700", letterSpacing: 0.7, marginTop: 3 },
  profileStatDivider: { width: 1, height: 28, backgroundColor: COLORS.line },
  journeyCard: { backgroundColor: COLORS.white, borderRadius: 18, paddingHorizontal: 14, paddingVertical: 5, borderWidth: 1, borderColor: "#EEEFE9" },
  journeyRow: { flexDirection: "row", alignItems: "center", gap: 11, paddingVertical: 11 },
  journeyIcon: { width: 37, height: 37, borderRadius: 12, backgroundColor: COLORS.paleGreen, alignItems: "center", justifyContent: "center" },
  journeyCopy: { flex: 1 },
  journeyLabel: { color: COLORS.muted, fontSize: 10 },
  journeyValue: { color: COLORS.ink, fontSize: 12, fontWeight: "700", marginTop: 3 },
  journeyRule: { height: 1, backgroundColor: COLORS.line, marginLeft: 48 },
  aboutCard: {
    flexDirection: "row",
    gap: 11,
    backgroundColor: "#FBF1E9",
    borderRadius: 17,
    padding: 14,
    marginTop: 14,
  },
  aboutIcon: { width: 34, height: 34, borderRadius: 11, backgroundColor: "#F8E4D3", alignItems: "center", justifyContent: "center" },
  aboutCopy: { flex: 1 },
  aboutTitle: { color: COLORS.ink, fontSize: 11, fontWeight: "700", marginTop: 1 },
  aboutText: { color: "#75685F", fontSize: 10, lineHeight: 15, marginTop: 5 },
  tabBar: {
    minHeight: 59,
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: COLORS.line,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingTop: 8,
  },
  tabItem: { flex: 1, alignItems: "center", justifyContent: "center", gap: 3, minHeight: 43 },
  tabLabel: { color: COLORS.muted, fontSize: 9, fontWeight: "600" },
  activeTabLabel: { color: COLORS.green, fontWeight: "700" },
});
